package api.medical.com.ApiMedica.ENUM;

public enum Especialidade {
    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA,
    CLINICO,
    PEDIATRIA,
    NEUROLOGIA,
    GASTROENTEROLOGIA,
    OFTALMOLOGIA,
    PSIQUIATRIA,
    ENDOCRINOLOGIA,
    OTORRINOLARINGOLOGIA,
    NEFROLOGIA,
    REUMATOLOGIA,
    ANESTESIOLOGIA,
    UROLOGIA,
    CIRURGIAO,
    ONCOLOGIA,
    ;

}
